---
version: 1
createdAt: '2022-03-03 12:12:00.000Z'
data:
- bookNo: https://librivox.org/don-quixote-vol-1-by-miguel-de-cervantes-saavedra/
  source: librivox
  id: 480
  title: Don Quixote - Vol. 1
  authors:
    - Miguel de Cervantes Saavedra
  language: English
  description: >
    Don Quixote is an early novel written by Spanish author Miguel de Cervantes
    Saavedra. Cervantes created a fictional origin for the story in the
    character of the Morisco historian, Cide Hamete Benengeli, whom he claims
    to have hired to translate the story from an Arabic manuscript he found in
    Toledo's bedraggled old Jewish quarter. The protagonist, Alonso Quixano,
    is a minor landowner who has read so many stories of chivalry that he
    descends into fantasy and becomes convinced he is a knight errant. Together
    with his companion Sancho Panza, the self-styled Don Quixote de la Mancha
    sets out in search of adventures. His lady is Dulcinea del Toboso, an
    imaginary object of his courtly love crafted from a neighbouring farm girl
    by the illusion-struck knight (her real name is Aldonza Lorenzo, and she is
    totally unaware of his feelings for her. In addition, she never actually
    appears in the novel).  Published in two volumes a decade apart, Don
    Quixote is the most influential work of literature to emerge from the
    Spanish Golden Age and perhaps the entire Spanish literary canon. As a
    founding work of modern Western literature, it regularly appears at or near
    the top of lists of the greatest works of fiction ever published. (Summary
    from Wikipedia)
- bookNo: https://librivox.org/brothers-karamazov-v3-by-fyodor-dostoyevsky/
  source: librivox
  id: 13837
  title: Brothers Karamazov (version 3)
  authors:
    - Fyodor Dostoyevsky
  language: English
  description: >
    Originally published in serial form in 1879-80, “The Brothers Karamazov” is
    recognized as one of the very greatest masterpieces of world literature. It
    is the last and finest novel of Fyodor Dostoyevsky, who died before writing
    a planned sequel. The story is organized initially around the efforts of
    adult sons to deal with their cantankerous and exasperating father. More
    important, they also have to deal with the problem of how to live in a
    world where it is difficult to be sure of the truth — whether that be
    “truth” about others, about oneself, or about deep questions such as faith,
    doubt, free will, guilt, and responsibility. Dostoyevsky’s technique
    underlines the difficulty of attaining sure knowledge. The novel’s
    psychological and philosophical depth sets the stage for modern novelists
    such as Joyce, Kafka, and Woolf. “The Brothers Karamazov” has been a
    favorite book for readers as diverse as Albert Einstein, Sigmund Freud,
    Joseph Stalin, Vladimir Putin, and Hillary Clinton. - Summary by Bruce Pirie
- bookNo: https://librivox.org/the-meditations-of-marcus-aurelius/
  source: librivox
  id: 1095
  title: The Meditations
  authors:
    - Marcus Aurelius
  language: English
  description: >
    Marcus Aurelius wrote Meditations in Greek while on campaign between 170
    and 180, as a source for his own guidance and self-improvement. These memos
    survive and continue to inspire others to this day. These writings take the
    form of quotations varying in length from one sentence to long paragraphs.
    He explicates the Stoic philosophy that the only way a man can be harmed by
    others is to allow his reaction to overpower him. He shows no particular
    religious faith in his writings, but seems to believe that some sort of
    logical, benevolent force organizes the universe in such a way that even
    "bad" occurrences happen for the good of the whole. (Summary by Ticktockman)
- bookNo: https://librivox.org/through-the-looking-glass-version-6-by-lewis-carroll/
  source: librivox
  id: 15261
  title: Through the Looking-Glass (Version 6)
  authors:
    - Lewis Carroll
  language: English
  description: >
    Through the Looking-Glass, and What Alice Found There (also known as Alice
    Through the Looking-Glass or simply Through the Looking-Glass) is an 1871
    novel by Lewis Carroll and the sequel to Alice's Adventures in Wonderland
    (1865). Alice again enters a fantastical world, this time by climbing
    through a mirror into the world that she can see beyond it. There she finds
    that, just like a reflection, everything is reversed, including logic.
    Alice becomes a player in a game of chess and works her way up to becoming
    a queen. On her way across the board she meets Tweedledum and Tweedledee,
    recites the classic poems, "Jabberwocky" and "The Walrus and the Carpenter",
    amongst many more. She also demonstrates her ability at mathematics to her
    new found friends, the red and white queens. The mirror that Alice ventured
    through is still on display in Charlton Kings, Gloucestershire. (Summary by
    Craig Franklin)
- bookNo: https://librivox.org/the-great-gatsby-2-by-f-scott-fitzgerald/
  source: librivox
  id: 16945
  title: The Great Gatsby (version 2)
  authors:
    - F. Scott Fitzgerald
  language: English
  description: >
    The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald.
    Set in the Jazz Age on Long Island, near New York City, the novel depicts
    first-person narrator Nick Carraway's interactions with mysterious
    millionaire Jay Gatsby and Gatsby's obsession to reunite with his former
    lover, Daisy Buchanan (Summary from Wikipedia)
- bookNo: https://librivox.org/crime-and-punishment-4-by-fyodor-dostoyevsky/
  source: librivox
  id: 10008
  title: Crime and Punishment (Version 4 Dramatic Reading)
  authors:
    - Fyodor Dostoyevsky
  language: English
  description: >
    The story tells of the inner turmoil of Rodion Raskolnikov, a student in
    St. Petersburg who commits murder. His psychological and moral agitation is
    furthered and complicated by his family's arrival in St. Petersburg, his
    sister's engagement to a manipulative and unworthy man, and his encounters
    with the impoverished and troubled Marmeladov family. Summary by Mary J.Cast
- bookNo: https://librivox.org/a-tale-of-two-cities-by-charles-dickens-5/
  source: librivox
  id: 15669
  title: A Tale of Two Cities (Version 5)
  authors:
    - Charles Dickens
  language: English
  description: >
    A Tale of Two Cities (1859) is a historical novel by Charles Dickens; it is
    moreover a moral novel strongly concerned with themes of guilt, shame,
    redemption and patriotism. The plot centers on the years leading up to
    French Revolution and culminates in the Jacobin Reign of Terror. It tells
    the story of two men, Charles Darnay and Sydney Carton, who look very alike
    but are entirely different in character.(Summary from Wikipedia)
- bookNo: https://librivox.org/the-diary-of-a-nobody-by-george-weedon-grossmith/
  source: librivox
  id: 336
  title: The Diary of a Nobody
  authors:
    - George Grossmith
    - Weedon Grossmith
  language: English
  description: >
    The Diary of a Nobody is the fictitious record of fifteen months in the life
    of Charles Pooter, his family, friends and small circle of acquaintances.
    It first appeared, serialised in Punch magazine and might be regarded as the
    first ‘blog’; being a record of the simplicities and humiliations in the
    life of this mundane, but upright, city clerk, who had an incontestable
    faith that a record of his daily life was worth preserving for posterity.
- bookNo: https://librivox.org/anna-karenina-deutsch-by-leo-tolstoy/
  source: librivox
  id: 10349
  title: Anna Karenina
  authors:
    - Leo Tolstoy
  language: German
  description: >
    Der Roman aus der Epoche des russischen Realismus gibt einen tiefgründigen
    Einblick in das Leben und die Lebensanschauungen der russischen Aristokratie
    des 19. Jahrhunderts. Mehr noch begeistert er durch die bis ins kleinste
    Detail mit großer Menschenkenntnis dargestellten Charaktere, deren Wesen
    Tolstoi uns weitestgehend durch ihre Art zu sprechen, denken, handeln und
    ihre "Kreise" auszuwählen näher bringt.
